### ISSUE TITLE
Mislabeled Scaler/Updater

### ISSUE THREAD

**Issue by malvidin** [CybercentreCanada/assemblyline-docker-compose#15]
The `al_scaler` image is listed as `al_updater`, and vice versa.

https://github.com/CybercentreCanada/assemblyline-docker-compose/blob/384f900a8b048e8d2be63bf50c2fb285c51d98ac/full_appliance/docker-compose.yaml#L245

**Comment by cccs-sgaron** [comment]
We will be moving to a helm based appliance very soon which is why we will not make any improvements to docker-compose. This will streamline the appliance deployment with the cliuster deployment. 

PR for helm is located here: https://github.com/CybercentreCanada/assemblyline-helm-chart/pull/15
