### ISSUE TITLE
wrong username and password

### ISSUE THREAD

**Issue by vector1one** [CybercentreCanada/assemblyline-docker-compose#2]
Hello, 

doing a minimal install.
everything installs great and runs no issue, but when I get to the webgui to log in ...either using either the default creds(admin/admin) or by changing the "./.env & ./config/bootstrap.py" to my own password I get the same "wrong username and password" error.

I installed and ran via
sudo docker-compose pull
sudo docker-compose up -d

thank you

**Comment by malvidin** [comment]
I recommend using the CLI to validate whether the accounts.
https://cybercentrecanada.github.io/assemblyline4_docs/docs/installation/deployment/appliance.html#access-the-assemblyline-cli

**Comment by mr-satan1** [comment]
Getting the same issue but with the 'full appliance' option. The assemblyline client 'user' options don't give me the ability to reset the password assigned to the admin user. It doesn't even show the admin user exists.

**Comment by cccs-rs** [comment]
Hello, 

If running either appliance OOB, you should perform the following commands in order (from appliance directory):
```
docker-compose pull
docker-compose up -d
docker-compose -f bootstrap-compose.yaml pull 
docker-compose -f bootstrap-compose.yaml up -d 
```
If this does not, please provide as much detail as possible to help diagnose this.

The bootstrap-compose.yaml registers the admin account in with the details in ./config/bootstrap.py.
