### ISSUE TITLE
Enhancement: Add "classification.yml" 

### ISSUE THREAD

**Issue by malvidin** [CybercentreCanada/assemblyline-docker-compose#8]
Recommend adding "classification.yml" from base to the config directory for both minimal and full, and for all of the docker-compose YAML files that include a volume for config.yml. 
These lines should be commented out in the YAML by default, to maintain the current behavior.

**Comment by cccs-sgaron** [comment]
We will be moving to a helm based appliance very soon which is why we will not make any improvements to docker-compose. This will streamline the appliance deployment with the cliuster deployment. 

PR for helm is located here: https://github.com/CybercentreCanada/assemblyline-helm-chart/pull/15
